**Exercise 1:**
Given a 2D list, create a numpy 2D array using it.

Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Print the Numpy array.

In [2]:
import numpy as np
list=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_array=np.array(list)
print(np_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Exercise 2:NumPy 0s and 1s**
Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
Print the elements of array.
Output Format :

    element1 element2 element3 ... 

In [3]:
import numpy as np
a=[0,0,0,0,1,0,0,0,0,0]
b=np.array(a,dtype=int)
for i in b:
    print(i,end=" ")

0 0 0 0 1 0 0 0 0 0 

**Exercise 3:**
Create an array with values ranging consecutively from 9 to 49 (both inclusive).
Print the Numpy array.

Output Format :

    element1 element2 element3 ...

In [4]:
a=np.arange(9,50)
for i in a:
    print(i,end=" ")

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

**Exercise 4:**
Create an integer identity matrix of size (5, 6).
Print the Numpy array.

Output Format :

    numpyArray

In [5]:
import numpy as np
a=np.eye(5,6,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


**Exercise 5:**
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
Print the array element.

Output Format :

    element1 
    element2 
    element3

In [6]:
a=np.linspace(0,5,10)
for i in a[1:9]:
    print(round(i,2))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


**Exercise 5:**
Given a 2D integer array size (4, 5) with name input_?
Print elements of highlighted matrix

In [7]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
print(input_)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


**Exercise 6 Non-Zero elements:**
Problem Statemnt:

    Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
    Print the index of non-zero elements.

Output Format :

    index1 index2 index3 ... 

In [8]:
a=np.array([1,2,0,0,4,0])
index=np.where(a!=0)
for i in index:
    pass
for m in i:
    print(m,end=" ")

0 1 4 

**Exercise 7 Multiples of 3:**

Problem Statement:
    
    Given an integer array of size 10. Print the index of elements which are multiple of 3.
    Note: Generate the following array
        array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
    Print the index of elements.

Output Format :

    index1 index2 index3 ... 

In [9]:
a=np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
index=np.where(a%3==0)
for i in index:
    pass
for m in i:
    print(m,end=" ")

1 4 7 

**Exercise 8 Odd elements:**

Problem Statemnt:

    Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
    Note: Generate the following array
        array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    Print the Numpy array.
    
Output Format :

    firstElement secondElement  ... 

In [10]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
index=np.where(a%2==1)
for i in index:
    pass
for m in i:
    a[m]=-1
for i in a:
    print(i, end=" ")

-1 2 -1 4 -1 6 -1 8 -1 10 

**Exercise 9 Replace Max:**

Problem Statemnt:

    Given an integer array of size 10 and replace the first occurrence of maximum value by 0?
    Note: Generate the following array
        array([11, 2, 13, 4, 15, 6, 27, 8, 19])
    Print the Numpy array.

Output Format :
    
    firstElement
    secondElement 
    ... 

In [11]:
a=np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
a[6]=0
for i in a:
    print(i)

11
2
13
4
15
6
0
8
19


**Exercise 10 Negate Elements:**

Problem Statemnt:
    
    Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
    Note: Generate the following array
        array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    Print the Numpy array.

Output Format :

    firstElement 
    secondElement  
    ... 

In [12]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
index=np.where((a>=3)&(a<=8))
index
for i in index:
    pass
for m in i:
    a[m]=-a[m]
for j in a:
    print(j)

1
2
-3
-4
-5
-6
-7
-8
9
10


**Exercise 11 Height:**

Problem Statemnt:

    Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
    Print the Numpy array.

Output Format :
    
    age1 height1 
    age2 height2 
    ... 

In [13]:
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
index=np.where(height>155)
for i in index:
    pass
for m in i:
    print(age[m],height[m])
print()

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172



**Exercise 12 Sort by column:**

Problem Statemnt:
    
    Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
    That means, we should re-arrange complete row based on 2nd columns' values.
    Given 2D array is:
         [[21 20 19 18 17]
          [16 15 14 13 12]
          [11 10  9  8  7]
          [ 6  5  4  3  2]]
    Print the 2D array in sorted order.
    Note you have to generate the 2D Array.Here 2nd column means column present at index 1.

Output Format :
     
    [[ 6  5  4  3  2]
    [11 10  9  8  7]
    [16 15 14 13 12]
    [21 20 19 18 17]]

In [14]:
a=[[21, 20, 19, 18, 17],[16, 15, 14, 13, 12],[11, 10,  9,  8,  7],[ 6,  5,  4,  3,  2]]
b=np.array(a)
c=b[:,1]#select out second column

#sort number of second colunm according to the big or small
d=[]
for i in c:
    d.append(i)
d.sort()
d

#find the corresponding index
e=[]
for i in d:
    for j in range(4):
        if b[j][1]==i:
            e.append(j)

#according to the index, reorder the array
f=[]
for index in e:
    f.append(b[index,:])

g=np.array(f)
print(g)  

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


**Exercise 13 Killed in USA:**

Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

Problem Statement :

    Find value of killed column only where country == ‘United States’?
    Print 0 in place of missing values.
    Print count of Killed as integer value.

Output Format :

    Killed1
    Killed2
    Killed3
    Killed4
    . . .


In [17]:
import csv
import numpy as np
data1=open('terrorismData.csv')
data=csv.DictReader(data1,skipinitialspace=True)

killed=[]
country=[]
for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    
np_killed=np.array(killed)
np_country=np.array(country)

np_killed[np_killed=='']='0.0'
np_killed=np.array(np_killed,dtype=float)
np_killed=np.array(np_killed,dtype=int)

bool_arr=np_country=='United States'
ans=np_killed[bool_arr]

for i in ans:
    print(i)    

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
4
0
1
1
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0


**Exercise 14 Total Killed in USA:**

Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

Problem Statement :

    Find total number of people killed from USA?
    Note: Some columns of killed are empty so replace them by 0.
    Print count of Killed as integer value.

Output Format :

    TotalKilled

In [16]:
import csv
import numpy as np
data1=open('terrorismData.csv')
data=csv.DictReader(data1,skipinitialspace=True)

killed=[]
country=[]
for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    
np_killed=np.array(killed)
np_country=np.array(country)

np_killed[np_killed=='']='0.0'
np_killed=np.array(np_killed,dtype=float)
np_killed=np.array(np_killed,dtype=int)

bool_arr=np_country=='United States'
ans=np_killed[bool_arr]
print(np.sum(ans)) 

3771
